### ISSUE TITLE
QTextEdit.setFontWeight() type error

### ISSUE THREAD

**Issue by bpabel** [chadrik/types-PySide#1]
This produces a type error:

```
self.setFontWeight(QtGui.QFont.DemiBold)
```

```
Argument of type "Weight" cannot be assigned to parameter "w" of type "int" in function "setFontWeight"
  "Weight" is incompatible with "int"
```

setFontWeight() allows QFont predefined weight enums, but they don't register as compatible with ints, even though they are

**Comment by chadrik** [comment]
Fixed in 5.2.1.1 on pypi.  Thanks for the report.
